name: hostel_night_mess_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_messaging: ^15.1.5
  cupertino_icons: ^1.0.8
  firebase_auth: 5.3.3
  google_sign_in: 6.2.2
  uuid: ^3.0.4
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Use version 5.0.0 instead of 5.1.0


dependency_overrides:
  async: ^2.12.0  # Latest version available
  boolean_selector: ^2.1.2
  characters: ^1.3.1
  clock: ^1.1.2
  collection: ^1.19.1
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  path: ^1.9.1
  stack_trace: ^1.12.0
  string_scanner: ^1.4.0
  test_api: ^0.7.4
  vm_service: ^14.3.1

flutter:
  uses-material-design: true
